version: 2

references:
  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  results_root: &results_root
    /tmp/results

  attach_results: &attach_results
    attach_workspace:
      at: *results_root

  composer: &composer
    run:
      name: Install composer dependencies
      command: composer update --prefer-lowest --no-interaction

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        # Move all files and dotfiles to current directory
        mv /tmp/workspace/php-email/* /tmp/workspace/php-email/.[!.]* .

  report_results: &report_results
    store_test_results:
      path: reports

  store_results: &store_results
    store_artifacts:
      path: *results_root
      destination: test_reports/

  push_coverage: &push_coverage
    run:
      name: Push the coverage reports to Codecov
      command: |
        bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'

jobs:
  checkout_code:
    working_directory: /home/circleci/php-email
    docker:
      - image: circleci/php:7.1-cli-node-browsers
    steps:
      - checkout
      - run:
          name: Copy checkout to workspace
          command: |
            mkdir -p /tmp/workspace/php-email
            mv * .[!.]* /tmp/workspace/php-email/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - php-email

  php71:
    working_directory: /home/circleci/php-email
    docker:
      - image: circleci/php:7.1-cli-node-browsers
    steps:
      - *attach_workspace
      - *load_code
      - *composer

      - run: mkdir reports
      - run: phpdbg -qrr vendor/bin/phpunit --log-junit "reports/junit-php71.xml" --coverage-clover="reports/coverage-php71.xml"

      - *report_results
      - *store_results
      - *push_coverage

  php72:
    working_directory: /home/circleci/php-email
    docker:
      - image: circleci/php:7.1-cli-node-browsers
    steps:
      - *attach_workspace
      - *load_code
      - *composer

      - run: mkdir reports
      - run: phpdbg -qrr vendor/bin/phpunit --log-junit "reports/junit-php72.xml" --coverage-clover="reports/coverage-php72.xml"

      - *report_results
      - *store_results
      - *push_coverage

workflows:
  version: 2

  build_and_test:
    jobs:
      - checkout_code
      - php71:
          requires:
            - checkout_code
      - php72:
          requires:
            - checkout_code
