version: 2

references:
  run_tests: &run_tests
    run:
      name: Run tests
      command: |
        # Ensure xdebug is installed
        sudo sh .circleci/install_xdebug.sh
        sh .circleci/test.sh

  workspace_root: &workspace_root
    /tmp/workspace

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

  results_root: &results_root
    /tmp/results

  attach_results: &attach_results
    attach_workspace:
      at: *results_root

  composer: &composer
    run:
      name: Install composer dependencies
      command: composer install

  load_code: &load_code
    run:
      name: load code from workspace
      command: |
        # Move all files and dotfiles to current directory
        mv /tmp/workspace/php-email/* /tmp/workspace/php-email/.[!.]* .

  report_results: &report_results
    store_test_results:
      path: reports

  persist_results: &persist_results
    persist_to_workspace:
      root: *results_root
      paths:
        - reports

  store_results: &store_results
    store_artifacts:
      path: *results_root
      destination: test_reports/

jobs:
  checkout_code:
    working_directory: /home/circleci/php-email
    docker:
      - image: notnoopci/php:5.6
    steps:
      - checkout
      - run:
          name: Copy checkout to workspace
          command: |
            mkdir -p /tmp/workspace/php-email
            mv * .[!.]* /tmp/workspace/php-email/
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - php-email

  php56:
    working_directory: /home/circleci/php-email
    docker:
      - image: notnoopci/php:5.6
    steps:
      - *attach_workspace
      - *load_code
      - *composer
      - run:
          name: Run tests
          command: |
            # Ensure xdebug is installed
            sudo sh .circleci/install_xdebug.sh
            sh .circleci/test.sh 56
      - *report_results
      - *persist_results

  php70:
    working_directory: /home/circleci/php-email
    docker:
      - image: notnoopci/php:7.0
    steps:
      - *attach_workspace
      - *load_code
      - *composer
      - run:
          name: Run tests
          command: |
            # Ensure xdebug is installed
            sudo sh .circleci/install_xdebug.sh
            sh .circleci/test.sh 70
      - *report_results
      - *persist_results

  php71:
    working_directory: /home/circleci/php-email
    docker:
      - image: notnoopci/php:7.1
    steps:
      - *attach_workspace
      - *load_code
      - *composer
      - run:
          name: Run tests
          command: |
            # Ensure xdebug is installed
            sudo sh .circleci/install_xdebug.sh
            sh .circleci/test.sh 71
      - *report_results
      - *persist_results

  codecov:
    working_directory: /home/circleci/php-email
    docker:
      - image: notnoopci/php:5.6
    steps:
      - *attach_results
      - *store_results

workflows:
  version: 2

  build_and_test:
    jobs:
      - checkout_code
      - php56:
          requires:
            - checkout_code
      - php70:
          requires:
            - checkout_code
      - php71:
          requires:
            - checkout_code
      - codecov:
          requires:
            - php56
            - php70
            - php71
